### ISSUE TITLE
AWS Lambda - crypto is undefined

### ISSUE THREAD

**Issue by jsmccrumb** [gr2m/universal-github-app-jwt#73]
When using `@octokit/auth-app` on AWS Lambda, node 18x, `crypto` is coming up as undefined.

A work around for that is importing `crypto` and setting it on `global`, but had to set `subtle` alias up:

```
import * as crypto from 'crypto';
global.crypto = {
   ...crypto,
  subtle: crypto.webcrypto.subtle,
}
```

Perhaps this package could be updated to `require` crypto if it is undefined, and instead of the alias `crypto.subtle` use the full path `crypto.webcrypto.subtle`? Not sure how that would effect it in other contexts though

**Comment by gr2m** [comment]
Most likely the problem is with how `@octokit/auth-app` is bundled before release. The problem should not occur if you use `universal-github-app-jwt` directly, could you test that please?

The solution for `@octokit/auth-app` is to turn it into an ES Module and take advantage of conditional exports like this package does, but that is a big project, that's been on hold for a while now, unfortunately: https://github.com/octokit/octokit-next.js

**Comment by jsmccrumb** [comment]
That makes sense, thanks, might be a bit before I can test it out but I'll let you know

**Comment by melroyvandenberg** [comment]
I have the same issue, you broke this package basically. I'm using `universal-github-app-jwt` directly :

```
The requested module '#crypto' does not provide an export named 'subtle'
```

![image](https://github.com/gr2m/universal-github-app-jwt/assets/66132222/6d78648c-e98f-4083-959f-b134c9e3b303)

```js
import githubAppJwt from "universal-github-app-jwt"

const { token, appId, expiration } = await githubAppJwt({ id: APP_ID, privateKey: PRIVATE_KEY })
```

Help..

**Comment by gr2m** [comment]
closing due to inactivty
